# Generated by Django 4.0.6 on 2022-10-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_post_likesnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likesNumber',
            field=models.IntegerField(),
        ),
    ]
